version: '3'
services:
  refresher:
    image: study-room-refresher
    build:
      context: refresher
    depends_on:
      - mariadb
      - backend
      - easyconnect
    environment:
      SQL_URL: studyroom-mariadb
      SQL_PORT: 3306
      DATABASE: studyroom
      SQL_USER: studyroom
      SQL_PASS: 123456
      CLASSES_USER: "TJU STUDENT ID"
      CLASSES_PASSWORD: "TJU CLASSES PASSWORD"
      IMMEDIATE: 1
      FETCH_DELTA: 7
      COOLDOWN_TIME: 0.6
      HTTP_PROXY: http://easyconnect:8888
      HTTPS_PROXY: http://easyconnect:8888
  backend:
    image: study-room-backend
    depends_on:
      - mariadb
    build:
      context: backend
    ports:
      - "8080:8080"
  mariadb:
    image: study-room-mariadb
    build:
      context: database
    hostname: studyroom-mariadb
    volumes:
      - ./database/data:/var/lib/mysql # persist data
    environment:
      MYSQL_USER: studyroom
      MYSQL_PASSWORD: 123456
    # do not expose any ports to ensure security
  easyconnect:
    image: hagb/docker-easyconnect:cli
    container_name: easyconnect
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - EC_VER=7.6.3
      - CLI_OPTS=-d vpn.tju.edu.cn -u [tju id] -p [tju vpn password]
    restart: unless-stopped

networks:
  study-room:
    driver: bridge
