server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/studyroom
    driver-class-name: org.mariadb.jdbc.Driver
    username: studyroom
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: StudyRoom
  integration:
    management:
      default-logging-enabled: false

jwt:
  name: Authorization
  expired: 7200000
  token: 123456
  prefix: Bearer
